// db/init.js — Auto-create all tables if they don't exist (Oracle-safe)
'use strict';
const db = require('./pool');

// Oracle doesn't support CREATE TABLE IF NOT EXISTS, so we check USER_TABLES first
async function tableExists(name) {
  const res = await db.execute(
    `SELECT COUNT(*) AS CNT FROM USER_TABLES WHERE TABLE_NAME = :name`,
    [name.toUpperCase()]
  );
  return res.rows[0].CNT > 0;
}

async function runDDL(label, sql) {
  try {
    await db.execute(sql);
    console.log(`  ✅ ${label}`);
  } catch (e) {
    console.error(`  ❌ ${label}: ${e.message}`);
  }
}

async function initTables() {
  console.log('\n🏗️  Initializing database tables...');

  // ── INV_USERS ─────────────────────────────────────────────────────────────
  if (!(await tableExists('INV_USERS'))) {
    await runDDL('CREATE INV_USERS', `
      CREATE TABLE INV_USERS (
        USER_ID        VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
        USERNAME       VARCHAR2(100)  UNIQUE NOT NULL,
        EMAIL          VARCHAR2(200)  UNIQUE NOT NULL,
        FULL_NAME      VARCHAR2(200)  NOT NULL,
        PASSWORD_HASH  VARCHAR2(300)  NOT NULL,
        ROLE           VARCHAR2(20)   DEFAULT 'USER' NOT NULL,
        IS_ACTIVE      NUMBER(1)      DEFAULT 1 NOT NULL,
        CREATED_AT     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
        LAST_LOGIN     TIMESTAMP
      )
    `);
    // Seed default admin
    const bcrypt = require('bcryptjs');
    const hash = bcrypt.hashSync('Admin@123', 10);
    await db.execute(
      `INSERT INTO INV_USERS (USERNAME, EMAIL, FULL_NAME, PASSWORD_HASH, ROLE)
       VALUES ('admin', 'admin@company.com', 'System Admin', :hash, 'ADMIN')`,
      { hash }
    );
    console.log('  👤 Default admin created: admin / Admin@123');
  }

  // ── INV_PROGRAMS ───────────────────────────────────────────────────────────
  if (!(await tableExists('INV_PROGRAMS'))) {
    await runDDL('CREATE INV_PROGRAMS', `
      CREATE TABLE INV_PROGRAMS (
        PROGRAM_ID   VARCHAR2(36)  DEFAULT SYS_GUID() PRIMARY KEY,
        CODE         VARCHAR2(50)  UNIQUE NOT NULL,
        NAME         VARCHAR2(200) NOT NULL,
        DESCRIPTION  VARCHAR2(500),
        IS_ACTIVE    NUMBER(1)     DEFAULT 1,
        CREATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
      )
    `);
    // Seed sample programs
    await db.execute(`INSERT INTO INV_PROGRAMS (CODE, NAME) VALUES ('PROG-001', 'Enterprise Mobility')`);
    await db.execute(`INSERT INTO INV_PROGRAMS (CODE, NAME) VALUES ('PROG-002', 'Field Operations')`);
    await db.execute(`INSERT INTO INV_PROGRAMS (CODE, NAME) VALUES ('PROG-003', 'IT Infrastructure')`);
  }

  // ── INV_PROJECTS ───────────────────────────────────────────────────────────
  if (!(await tableExists('INV_PROJECTS'))) {
    await runDDL('CREATE INV_PROJECTS', `
      CREATE TABLE INV_PROJECTS (
        PROJECT_ID   VARCHAR2(36)  DEFAULT SYS_GUID() PRIMARY KEY,
        PROGRAM_ID   VARCHAR2(36)  REFERENCES INV_PROGRAMS(PROGRAM_ID),
        CODE         VARCHAR2(50)  UNIQUE NOT NULL,
        NAME         VARCHAR2(200) NOT NULL,
        DESCRIPTION  VARCHAR2(500),
        IS_ACTIVE    NUMBER(1)     DEFAULT 1,
        CREATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
      )
    `);
  }

  // ── INV_DEVICES ────────────────────────────────────────────────────────────
  if (!(await tableExists('INV_DEVICES'))) {
    await runDDL('CREATE INV_DEVICES', `
      CREATE TABLE INV_DEVICES (
        DEVICE_ID      VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
        IMEI           VARCHAR2(20)   UNIQUE NOT NULL,
        SERIAL_NUMBER  VARCHAR2(100)  UNIQUE,
        MAKE           VARCHAR2(50)   NOT NULL,
        MODEL          VARCHAR2(100)  NOT NULL,
        COLOR          VARCHAR2(30),
        STORAGE        VARCHAR2(20),
        OS_TYPE        VARCHAR2(20),
        OS_VERSION     VARCHAR2(50),
        PURCHASE_DATE  DATE,
        WARRANTY_DATE  DATE,
        NOTES          VARCHAR2(1000),
        STATUS         VARCHAR2(25)   DEFAULT 'AVAILABLE' NOT NULL,
        CREATED_AT     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
        CREATED_BY     VARCHAR2(100)
      )
    `);
    await runDDL('CREATE INDEX IDX_DEVICES_STATUS', `CREATE INDEX IDX_DEVICES_STATUS ON INV_DEVICES(STATUS)`);
    await runDDL('CREATE INDEX IDX_DEVICES_IMEI',   `CREATE INDEX IDX_DEVICES_IMEI ON INV_DEVICES(IMEI)`);
  }

  // ── INV_ASSIGNMENTS ────────────────────────────────────────────────────────
  if (!(await tableExists('INV_ASSIGNMENTS'))) {
    await runDDL('CREATE INV_ASSIGNMENTS', `
      CREATE TABLE INV_ASSIGNMENTS (
        ASSIGNMENT_ID    NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        DEVICE_ID        VARCHAR2(36)   NOT NULL REFERENCES INV_DEVICES(DEVICE_ID),
        ASSIGNMENT_TYPE  VARCHAR2(20)   NOT NULL,
        ASSIGNED_TO_NAME VARCHAR2(200),
        ASSIGNED_TO_USER VARCHAR2(36)   REFERENCES INV_USERS(USER_ID),
        PROGRAM_ID       VARCHAR2(36)   REFERENCES INV_PROGRAMS(PROGRAM_ID),
        PROJECT_ID       VARCHAR2(36)   REFERENCES INV_PROJECTS(PROJECT_ID),
        ASSIGNED_BY      VARCHAR2(36)   REFERENCES INV_USERS(USER_ID),
        ASSIGNED_DATE    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
        EXPECTED_RETURN  DATE,
        RETURN_DATE      TIMESTAMP,
        IS_ACTIVE        NUMBER(1)      DEFAULT 1,
        NOTES            VARCHAR2(1000)
      )
    `);
    await runDDL('CREATE INDEX IDX_ASSIGN_DEVICE', `CREATE INDEX IDX_ASSIGN_DEVICE ON INV_ASSIGNMENTS(DEVICE_ID)`);
    await runDDL('CREATE INDEX IDX_ASSIGN_ACTIVE', `CREATE INDEX IDX_ASSIGN_ACTIVE ON INV_ASSIGNMENTS(IS_ACTIVE)`);
  }

  // ── INV_AUDIT ──────────────────────────────────────────────────────────────
  if (!(await tableExists('INV_AUDIT'))) {
    await runDDL('CREATE INV_AUDIT', `
      CREATE TABLE INV_AUDIT (
        AUDIT_ID    NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        DEVICE_ID   VARCHAR2(36),
        ACTION      VARCHAR2(50)  NOT NULL,
        ENTITY_TYPE VARCHAR2(50),
        ENTITY_ID   VARCHAR2(36),
        OLD_VALUE   VARCHAR2(2000),
        NEW_VALUE   VARCHAR2(2000),
        CHANGED_BY  VARCHAR2(100),
        CHANGED_AT  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
      )
    `);
    await runDDL('CREATE INDEX IDX_AUDIT_DEVICE', `CREATE INDEX IDX_AUDIT_DEVICE ON INV_AUDIT(DEVICE_ID)`);
    await runDDL('CREATE INDEX IDX_AUDIT_DATE',   `CREATE INDEX IDX_AUDIT_DATE ON INV_AUDIT(CHANGED_AT)`);
  }

  console.log('🏁 Database initialization complete.\n');
}

module.exports = { initTables };
